### ISSUE TITLE
produce/consumme warnings with Julia 0.6

### ISSUE THREAD

**Issue by s-celles** [pdobacz/PyTest.jl#5]
Hello,

A lot of warnings are shown with Julia 0.6.
It's also mentionned in https://github.com/pdobacz/PyTest.jl/blame/c06d78c97ce1e2c90bbd202dbb653832d9f14e3a/README.md#L13

What about using [Channels](https://docs.julialang.org/en/latest/manual/parallel-computing#Channels-1)?

See also
https://discourse.julialang.org/t/pygen-python-style-generators/3451/30
https://discourse.julialang.org/t/ann-resumablefunctions/5711

Kind regards

**Comment by pdobacz** [comment]
I agree the warnings are pretty icky.

Back when I was doing `v0.6` compatibility I was looking through the options, but went with "wait and see". I vaguely recall a discussion spotted somewhere, that the "old way" of doing this - similar to `produce`/`consume` might be supported again. Haven't looked at this since.

Switching to Channels seemed to go beyond a "quick fix" at first glance, and kind of overkill.

Ah, so `ResumableFunctions` looks very interesting, thanks for the suggestion! I wonder if it will work in this context. `PyGen` also seems feasible. I might give them a try, but not immediately now, sadly... unless you want to take a stab at it :).

**Comment by pdobacz** [comment]
That was fun. Fixed in https://github.com/pdobacz/PyTest.jl/commit/068fa0df12768b637ede1a348f9c51b1facd88a7, tidied in https://github.com/pdobacz/PyTest.jl/releases/tag/v0.1.0. I used `ResumableFunctions.jl`, thanks for the suggestion.
